### ISSUE TITLE
filtering: choose the filter order

### ISSUE THREAD

**Issue by fabienBourban** [mmlabs-mindmaze/mcpanel#4]
We can choose in the interface the low and high pass frequencies of the filter. Would it be possible to expose als the ability to the user to choose the order of the filter?

This can be usefull to have a filter of higher order especially for power line noise removal.

**Comment by nbourdau** [comment]
PR opened at https://review.gerrithub.io/c/mmlabs-mindmaze/mcpanel/+/499566/6
