### ISSUE TITLE
spectrum panel: data remains after reconnection

### ISSUE THREAD

**Issue by fabienBourban** [mmlabs-mindmaze/mcpanel#5]
After you select a channel to see its frequency spectrum if you disconnect then connect again, you will still have the last image of the spectrum from the previous connection. 

The spectrum should be cleared when clicking on "Connect" like is is the case for the signal in "EEG" panel.

**Comment by nbourdau** [comment]
PR opened at https://review.gerrithub.io/c/mmlabs-mindmaze/mcpanel/+/499564
